# Workflow Name
name : First Workflow
# Trigger
on : 
  push :
  workflow_dispatch: # manual
 
jobs:
   # First Job
  Hello-job:
     # runner - Github hosted
     runs-on : ubuntu-latest
     steps:
       - name : Hello World
         run : echo "Hello World"
       - name : Event Name
         run : echo "Event Name :${{github.event_name}}" # Context Reference

 
 
  # Second Job
  echo-goodbye:
    needs : Hello-job
    runs-on : ubuntu-slim
    steps:
      - name: Say Goodbye
        run: echo "Goodbye!"
      # Multiple commands
      - name : Multi-line bash
        run : |
         echo "I am"
         echo "multi-line"
         echo "script"
 
  # third job
  windows-echo:
   if: github.event_name == 'workflow_dispatch'
   runs-on: windows-latest
   steps:
     - name : Show OS
     
  shell : bash
       run : echo "The job is running on Windows runner."
